GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "Blog for chicks",
    "author": "jajaja pepe",
    "url": "www.porns.com",
    "likes": 9
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NmU1NzVkNWViNzMzYjI1NmJlOGQ2NyIsImlhdCI6MTY4ODQyNzY2MywiZXhwIjoxNjg4NDI3NzIzfQ.T8fwZY8hhWaoqnd3UflGO7UQjqIjUTmQV8ZtWiwSuGU

{
    "title": " septimo blog de pepito perez",
    "author": "javichu garcia moreno",
    "url": "www.jajaja.com",
    "likes": 9
}

###
DELETE http://localhost:3003/api/blogs/64a30e8c94f161d6ef51e2bb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NmU1NzVkNWViNzMzYjI1NmJlOGQ2NyIsImlhdCI6MTY4ODQyMzY2NX0.EnBHSl6NDe-dnc3zUZze3oVKIQOuZy37S-RxhwliMRw

###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "pepe",
    "name": "Jose Perez",
    "password":""  
}


### ver username and password en .env
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "",
    "password": ""   
}

### ver username and password en .env
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "",   
    "password": ""
}


### comprobacion de token expirado o invalido
GET http://localhost:3003/api/blogs/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGUiLCJpZCI6IjY0NmY5ODQwMTdiNGI4YmMxYTRiZTU2NiIsImlhdCI6MTY4NTc0OTMyMiwiZXhwIjoxNjg1ODM1NzIyfQ.S9umieCRSBzBZ2eMmAPwjyP0eh2HDRBPdO_Zp4JDAG4


### devolucion de los blogs de un usuario determinado
Get http://localhost:3003/api/blogs/usuario/646f984017b4b8bc1a4be566