GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "Blog for chicks",
    "author": "jajaja pepe",
    "url": "www.porns.com",
    "likes": 9
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGUiLCJpZCI6IjY0NmY5ODQwMTdiNGI4YmMxYTRiZTU2NiIsImlhdCI6MTY4NTAzOTE4MH0.gPAQX47BXUwJ3otgjIK7ggRFV--RBuYuEw2GWL4-koA

{
    "title": "Blog for golf",
    "author": "pepe asdf",
    "url": "www.porns.com",
    "likes": 6
}

###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "pepe",
    "name": "Jose Perez",
    "password":"ffas"
  
}


###
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "pepe",
    "password": "pepe99"   
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "root",   
    "password": "salainen"
}

