GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "Blog for chicks",
    "author": "jajaja pepe",
    "url": "www.porns.com",
    "likes": 9
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGUiLCJpZCI6IjY0NmY5ODQwMTdiNGI4YmMxYTRiZTU2NiIsImlhdCI6MTY4NTQ4MzcyOSwiZXhwIjoxNjg1NTcwMTI5fQ.duO_vK1SMJ3aN1hgaL-8TyPEIU0E92JNg7Axm2T3t3Q

{
    "title": "Blog del gugug",
    "author": "pepe asdf",
    "url": "www.porns.com",
    "likes": 6
}

###
DELETE http://localhost:3003/api/blogs/647673fe8f3e22001be82225 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGUiLCJpZCI6IjY0NmY5ODQwMTdiNGI4YmMxYTRiZTU2NiIsImlhdCI6MTY4NTQ4MzcyOSwiZXhwIjoxNjg1NTcwMTI5fQ.duO_vK1SMJ3aN1hgaL-8TyPEIU0E92JNg7Axm2T3t3Q

###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "pepe",
    "name": "Jose Perez",
    "password":"ffas"
  
}


###
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "pepe",
    "password": "pepe99"   
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "root",   
    "password": "salainen"
}

